print(" ")
input("Enter your First Number: ")
input("Enter Operation (+, -, *, /): ")
input("Enter your Second Number: ")
print("Hello, World!")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
